// wire_gen.go contains the dependency-injection wiring. In the reference
// architecture this file is generated by `make wire` from the provider set in
// container.go; here it is hand-authored but kept in the same shape — a single
// InitializeApp constructor that builds the object graph bottom-up.
//
// Edit container.go's provider notes and keep this in sync.
package di

import (
	"context"
	"fmt"

	"github.com/kharchibook/auth-service/config"
	"github.com/kharchibook/auth-service/drivers"
	"github.com/kharchibook/auth-service/pkg/domain/service"
	"github.com/kharchibook/auth-service/pkg/infrastructure/blindindex"
	"github.com/kharchibook/auth-service/pkg/infrastructure/cacherepo"
	"github.com/kharchibook/auth-service/pkg/infrastructure/kms"
	"github.com/kharchibook/auth-service/pkg/infrastructure/msgqueuerepo"
	"github.com/kharchibook/auth-service/pkg/infrastructure/sqlrepo"
	httptransport "github.com/kharchibook/auth-service/pkg/infrastructure/transport/http"
	"github.com/kharchibook/auth-service/third_party/platlogger"
)

// InitializeApp builds the full application object graph from configuration.
func InitializeApp(cfg *config.Config) (AppInterface, error) {
	// --- drivers (external infrastructure) ---
	db, err := drivers.NewPostgres(cfg.Store)
	if err != nil {
		return nil, fmt.Errorf("init postgres: %w", err)
	}
	rdb, err := drivers.NewRedis(cfg.Cache)
	if err != nil {
		return nil, fmt.Errorf("init redis: %w", err)
	}

	// --- infrastructure repositories ---
	userRepo := sqlrepo.NewUserRepository(db)
	sessionRepo := sqlrepo.NewSessionRepository(db)
	rbacRepo := sqlrepo.NewRBACRepository(db)
	auditRepo := sqlrepo.NewAuditRepository(db)
	gmailCredRepo := sqlrepo.NewGmailCredentialRepository(db)

	otpRepo := cacherepo.NewOTPRepository(rdb)
	resetRepo := cacherepo.NewResetTokenRepository(rdb)
	rateLimitRepo := cacherepo.NewRateLimitRepository(rdb)

	// Use the SMTP publisher when email is configured (Username set via env);
	// otherwise fall back to the logging stub so local dev needs no provider.
	var publisher msgqueuerepo.INotificationPublisher
	if cfg.Email.Host != "" && cfg.Email.Username != "" {
		publisher = msgqueuerepo.NewSMTPPublisher(cfg.Email)
	} else {
		publisher = msgqueuerepo.NewStubPublisher()
	}
	googleClient := httptransport.NewGoogleOAuthClient(cfg.OAuth.Google)
	gmailClient := httptransport.NewGmailOAuthClient(cfg.OAuth.Google)

	encryptor, err := kms.NewLocalKMS("")
	if err != nil {
		return nil, fmt.Errorf("init kms: %w", err)
	}
	phoneHasher := blindindex.New(cfg.Internal.PhoneHashKey)

	// --- domain services (built bottom-up) ---
	passwordSvc := service.NewPasswordService(cfg.Security.BcryptCost)
	tokenSvc, err := service.NewTokenService(cfg.Token)
	if err != nil {
		return nil, fmt.Errorf("init token service: %w", err)
	}
	auditSvc := service.NewAuditService(auditRepo)
	rbacSvc := service.NewRBACService(rbacRepo)
	accountSvc := service.NewAccountService(
		userRepo, rbacSvc, encryptor, phoneHasher,
		cfg.Security.MaxFailedAttempts, cfg.Security.AccountLockDuration,
	)

	// Backfill the phone blind index for any rows that predate the column.
	// Best-effort and idempotent — a failure here must not block startup.
	if n, err := accountSvc.BackfillPhoneHashes(context.Background()); err != nil {
		platlogger.Warn("phone-hash backfill failed", "error", err)
	} else if n > 0 {
		platlogger.Info("phone-hash backfill complete", "updated", n)
	}
	sessionSvc := service.NewSessionService(sessionRepo, tokenSvc)
	gmailSvc := service.NewGmailTokenService(gmailClient, gmailCredRepo, encryptor, cfg.Internal.APIKey)

	devMode := cfg.App.Env == "dev"
	otpSvc := service.NewOTPService(otpRepo, publisher, cfg.OTP, devMode)

	authSvc := service.NewAuthService(service.AuthDeps{
		Accounts:  accountSvc,
		Passwords: passwordSvc,
		Tokens:    tokenSvc,
		Sessions:  sessionSvc,
		OTP:       otpSvc,
		RBAC:      rbacSvc,
		Audit:     auditSvc,
		ResetRepo: resetRepo,
		RateLimit: rateLimitRepo,
		Publisher: publisher,
		Google:    googleClient,
		RateCfg:   cfg.RateLimit,
		ResetURL:  cfg.App.ResetPasswordURL,
		DevMode:   devMode,
	})

	return &app{
		cfg:        cfg,
		authSvc:    authSvc,
		tokenSvc:   tokenSvc,
		rbacSvc:    rbacSvc,
		accountSvc: accountSvc,
		gmailSvc:   gmailSvc,
		db:         db,
		rdb:        rdb,
	}, nil
}
